Fixed chunker chunk length calculation
supabase/auth-helpers pull request #680
Opened 2023-11-09 10:14 UTC by dvvolynkin

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

[Cookie is too large](https://github.com/supabase/auth-helpers/issues/643)
Value not encoded before splitting. 
Sometimes, this causes too big chunks because the encoded cookie value length is longer than not encoded.

## What is the new behavior?
Added splitting by encoded value

2023-11-10 12:00 UTC, silentworks commented
Thank you for this PR. We just need to test it out and make sure the unit tests for the chunker is still passing and then we can get this merged in.

2023-11-10 22:06 UTC, silentworks commented
Unit tests are failing on this change, the chunk length returned is always 1 which cannot be correct.

2023-11-10 22:13 UTC, silentworks commented on packages/ssr/src/utils/chunker.ts
> +	return new RegExp(`(.{1,${chunkSize}})(?=%[0-9A-Fa-f]{2}|$)`, 'g');
Why this change to the Regex?

2023-11-11 05:50 UTC, dvvolynkin commented on packages/ssr/src/utils/chunker.ts
> +	return new RegExp(`(.{1,${chunkSize}})(?=%[0-9A-Fa-f]{2}|$)`, 'g');
Yep, it was a mistake
Changing it back

2023-11-11 05:51 UTC, dvvolynkin commented
@silentworks 
Changed regexp back, now tests are passing 

Sorry that haven't checked the tests in the first commit.

2023-11-13 09:05 UTC, dvvolynkin commented
@silentworks 
Added test for encoded string and fixed bug in my code

2023-11-14 05:03 UTC, silentworks commented
@dvvolynkin you've made too many logic change in this code, please revert the logic to what it was before as your changes are complicating the code.

2023-11-14 05:05 UTC, silentworks requested changes
You've made too many logic change in this code, please revert the logic to what it was before as your changes are complicating the code.

2023-11-14 05:29 UTC, dvvolynkin commented
@silentworks okay

I revert all logic of chunker and leave a test that is not passing.
You can implement a logic in your style.

2023-11-14 05:40 UTC, dvvolynkin commented
1. Cookie value should be splitted into chunks that length can fit 4096 symbols **after encoding**. 
2. If you use the initial regexp on the encoded string then you will face that your chunks can be broken because of % sequence.

2024-01-31 07:17 UTC, kangmingtay commented
hi @dvvolynkin, thanks for working with @silentworks to hash out the possible solutions we can take to chunk the cookies correctly. just an update, we've decided to go with this approach: https://github.com/supabase/auth-helpers/pull/726 so i'll be closing this PR

2024-01-31 07:17 UTC, closed without merging