fix(chunker): Fix chunk length calculation for unicode characters
supabase/auth-helpers pull request #726
Opened 2024-01-25 04:39 UTC by SyntheticGoop

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

The length of cookies with URI escaped characters can exceed the valid cookie length of 4096, causing parts of the split cookies to be rejected by the browser.

## What is the new behavior?

Chunked cookies after URI encoding now fit within the chunk size specified.

## Additional context

The reason for this issue occurring is that we are chunking base on lengths before escaping. While we have some buffer in the `MAX_CHUNK_SIZE` for longer unicode characters, this does not always work.

For example `﷽` has a length in javascript of `1` as well as match `/(.{1})/g.exec("﷽") ` to be `$1 = ﷽`, but it will escape to `%EF%B7%BD` which is 9 characters long.

The current approach of chunking with a buffer for some unicode characters will never be "correct" unless we implement a buffer that accounts for every character being a maximum size unicode.

I've reimplemented the createChunks function to do the following:
1. Split the chunk after encoding it.
2. Ensure that chunks are split correctly between unicode characters instead of inside of it.
3. Not use regex as it is hard to determine what a "correct" unicode character boundary is in regex when it is escaped.

There are currently other related solutions and issues:

__PRs__
- #680
- #701

__Issues__
- #707 
- #715

2024-01-26 17:39 UTC, imcat0131 approved these changes

2024-01-26 17:41 UTC, sscr197 approved these changes

2024-01-26 18:46 UTC, imcat0131 requested changes
ssr/src/utils/chunker.ts in the diffs of this Pull Request should be updated as follows, due to TypeScript constraints:
```ts
	 return chunks.map((value, i) => ({
		name: `${key}.${i}`,
		value: value as string // 明示的にstring型を示す
	  }));
```

2024-01-26 20:57 UTC, imcat0131 commented
@SyntheticGoop
Hey! Your pull request was exactly what I wanted. However, when I forked and used it, a problem seemed to occur when deploying Vercel. The functions to make it work are presented above. The problem was a simple Typescript constraint.

2024-01-27 04:15 UTC, SyntheticGoop commented
> @SyntheticGoop Hey! Your pull request was exactly what I wanted. However, when I forked and used it, a problem seemed to occur when deploying Vercel. The functions to make it work are presented above. The problem was a simple Typescript constraint.

I've updated the types so that the package build on my system with `pnpm build`.

2024-01-30 10:43 UTC, kangmingtay approved these changes

2024-01-30 10:46 UTC, merged

2024-01-30 11:34 UTC, SyntheticGoop commented on packages/ssr/src/utils/chunker.ts
> +		if (lastEscapePos > resolvedChunkSize - 3) {
Yes that's exactly it.